---
# These tasks sets up the vagrant machine for databases

- name: Pull containers
  shell: "docker pull {{item}}"
  with_items:
    - "{{ db_image }}:{{ db_version }}"
    - "sumanmukherjee03/ambassador:1.0"
  when: install_docker_py|success

- name: Remove existing db ambassador container
  docker:
    name: db_ambassador
    image: "sumanmukherjee03/ambassador:1.0"
    state: absent
  register: removed_db_ambassador_container

- name: Remove existing db container
  docker:
    name: "{{ db_container_name }}"
    image: "{{ db_image }}:{{ db_version }}"
    state: absent
  register: removed_db_container

- name: Start db container
  docker:
    name: "{{ db_container_name }}"
    image: "{{ db_image }}:{{ db_version }}"
    hostname: "{{ db_hostname }}"
    env:
      USER: "{{ db_user }}"
      PASSWD: "{{ db_passwd }}"
    detach: True
    state: started
  when: removed_db_ambassador_container|success and removed_db_container|success
  register: started_db_container

- name: Start db ambassador container
  docker:
    name: db_ambassador
    image: "sumanmukherjee03/ambassador:1.0"
    hostname: "{{ db_hostname }}_ambassador"
    links:
      - "{{ db_container_name }}:{{ db_container_name }}"
    ports:
      - "{{ db_port }}:{{ db_port }}"
    expose:
      - "{{ db_port }}"
    detach: True
    state: started
  when: started_db_container|success
