---
# These tasks sets up common stuff on the servers and checks dns routing

- name: Checks if resolver is working properly for carrying out further tasks
  command: host -t A google.com
  register: ns

- name: Pushes deploy users github private key to the remote developer users ssh keys
  copy: src="/Users/suman/.ssh/github/{{ item }}" dest="/home/developer/.ssh/{{ item }}" group=developer owner=developer mode=0600
  with_items:
    - id_rsa
    - id_rsa.pub

- name: Add github as a known host to the ssh config of developer user
  shell: >
    ssh-keyscan -H github.com >> /home/developer/.ssh/known_hosts && chmod 600 /home/developer/.ssh/known_hosts
  sudo: no
