---
# These tasks setup consul-template

- name: Install apt packages
  apt: "name='{{ item }}' state=present update_cache=yes install_recommends=no"
  with_items:
    - unzip

- command: test -s /usr/local/bin/consul-template
  ignore_errors: yes
  register: consul_template_installed

- name: Install consul-template binary
  shell: >
    cd /usr/local/bin &&
    curl -O https://releases.hashicorp.com/consul-template/0.12.0/consul-template_0.12.0_linux_amd64.zip &&
    unzip consul-template_0.12.0_linux_amd64.zip &&
    rm consul-template_0.12.0_linux_amd64.zip
  when: consul_template_installed|failed
