---
# These tasks pull the containers

- name: Pull dns container
  shell: "docker pull {{item}}"
  with_items:
    - "{{ image }}:{{ tag }}"
  when: install_docker_py|success

- name: Remove existing consul agent container
  docker:
    name: "{{ consul_container_name }}"
    image: "{{ image }}:{{ tag }}"
    state: absent

- name: Start dns container
  docker:
    name: "{{ container_name }}"
    image: "{{ image }}:{{ tag }}"
    ports:
      - "{{ ansible_ssh_host }}:53:53/udp"
    volumes:
      - "/etc/dnsmasqhosts:/etc/dnsmasqhosts"
    detach: True
    state: started

- file: path=/tmp/dnsmasqhosts state=directory owner=root group=root
- file: path=/etc/dnsmasqhosts state=directory owner=root group=root

- name: Copy dnsmasq hosts files
  copy: >
    src="{{ item }}"
    dest=/tmp/dnsmasqhosts/
  with_fileglob:
    - ../files/services.ctmpl
  register: dnsmasq_hosts_ready

- name: Start consul-template daemon
  shell: >
    nohup consul-template -consul "{{ first_consul_server_ip }}:8500" \
      -wait 2s \
      -retry 5s \
      -pid-file /var/run/consul-template.pid \
      -template '/tmp/dnsmasqhosts/services.ctmpl:/etc/dnsmasqhosts/services:docker restart dnsmasqServer' \
      >/dev/null 2>&1 &
  when: dnsmasq_hosts_ready|success
