FROM sumanmukherjee03/nvm:0.23.2
MAINTAINER Suman Mukherjee <sumanmukherjee03@gmail.com>

RUN apt-get -qq update

RUN source /.bash_profile && nvm install 0.10.29
RUN source /.bash_profile && nvm alias default v0.10.29
